# Generated by Django 4.2.7 on 2023-11-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('crim_id', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=200)),
                ('nation_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('report', models.TextField()),
            ],
        ),
    ]
